// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PRN222_TrackingTool.DataAccessLayer.Context;

#nullable disable

namespace PRN222_TrackingTool.DataAccessLayer.Migrations
{
    [DbContext(typeof(Prn222TrackingToolContext))]
    partial class Prn222TrackingToolContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PRN222_TrackingTool.DataAccessLayer.Entities.Exam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int?>("Duration")
                        .HasColumnType("integer")
                        .HasColumnName("duration");

                    b.Property<int?>("ExaminerId")
                        .HasColumnType("integer")
                        .HasColumnName("examiner_id");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("PK__Exams__3213E83FF9197BD1");

                    b.HasIndex("ExaminerId");

                    b.ToTable("Exams");
                });

            modelBuilder.Entity("PRN222_TrackingTool.DataAccessLayer.Entities.LecturerStudentAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AssignedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("assigned_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<bool?>("IsFinal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_final");

                    b.Property<bool?>("IsReExam")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_re_exam");

                    b.Property<int>("LecturerId")
                        .HasColumnType("integer");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.Property<double?>("Score")
                        .HasColumnType("double precision")
                        .HasColumnName("score");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer");

                    b.Property<int>("TestId")
                        .HasColumnType("integer");

                    b.HasKey("Id")
                        .HasName("PK_LecturerStudentAssignment");

                    b.HasIndex("LecturerId");

                    b.HasIndex("StudentId");

                    b.HasIndex("TestId");

                    b.ToTable("LecturerStudentAssignments");
                });

            modelBuilder.Entity("PRN222_TrackingTool.DataAccessLayer.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("PK__Roles__3213E83F12FB5F9F");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("PRN222_TrackingTool.DataAccessLayer.Entities.Students", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("fullname");

                    b.Property<string>("StudentCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("student_code");

                    b.HasKey("Id")
                        .HasName("PK__Students__3213E83F92C3D8B1");

                    b.ToTable("Students", (string)null);
                });

            modelBuilder.Entity("PRN222_TrackingTool.DataAccessLayer.Entities.Test", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<string>("Content")
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<int?>("ExamId")
                        .HasColumnType("integer")
                        .HasColumnName("exam_id");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("Link")
                        .HasColumnType("text")
                        .HasColumnName("link");

                    b.Property<string>("OriginalFilename")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("original_filename");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer")
                        .HasColumnName("student_id");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("PK__Tests__3213E83F8B8D01C8");

                    b.HasIndex("ExamId");

                    b.HasIndex("StudentId")
                        .IsUnique();

                    b.ToTable("Tests");
                });

            modelBuilder.Entity("PRN222_TrackingTool.DataAccessLayer.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<DateTime?>("ExpiredRefreshToken")
                        .HasColumnType("timestamptz")
                        .HasColumnName("expired_refresh_token");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text")
                        .HasColumnName("refresh_token");

                    b.Property<int?>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("PK__Users__3213E83F76EF0D74");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PRN222_TrackingTool.DataAccessLayer.Entities.Exam", b =>
                {
                    b.HasOne("PRN222_TrackingTool.DataAccessLayer.Entities.User", "Examiner")
                        .WithMany("Exams")
                        .HasForeignKey("ExaminerId")
                        .HasConstraintName("FK__Exams__examiner___412EB0B6");

                    b.Navigation("Examiner");
                });

            modelBuilder.Entity("PRN222_TrackingTool.DataAccessLayer.Entities.LecturerStudentAssignment", b =>
                {
                    b.HasOne("PRN222_TrackingTool.DataAccessLayer.Entities.User", "Lecturer")
                        .WithMany("LecturerStudentAssignments")
                        .HasForeignKey("LecturerId")
                        .IsRequired()
                        .HasConstraintName("FK_LecturerStudentAssignment_Lecturer");

                    b.HasOne("PRN222_TrackingTool.DataAccessLayer.Entities.Students", "Student")
                        .WithMany("LecturerStudentAssignments")
                        .HasForeignKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("FK_LecturerStudentAssignment_Student");

                    b.HasOne("PRN222_TrackingTool.DataAccessLayer.Entities.Test", "Test")
                        .WithMany("LecturerStudentAssignments")
                        .HasForeignKey("TestId")
                        .IsRequired()
                        .HasConstraintName("FK_LecturerStudentAssignment_Test");

                    b.Navigation("Lecturer");

                    b.Navigation("Student");

                    b.Navigation("Test");
                });

            modelBuilder.Entity("PRN222_TrackingTool.DataAccessLayer.Entities.Test", b =>
                {
                    b.HasOne("PRN222_TrackingTool.DataAccessLayer.Entities.Exam", "Exam")
                        .WithMany("Tests")
                        .HasForeignKey("ExamId")
                        .HasConstraintName("FK__Tests__exam_id__45F365D3");

                    b.HasOne("PRN222_TrackingTool.DataAccessLayer.Entities.Students", "Student")
                        .WithOne("Test")
                        .HasForeignKey("PRN222_TrackingTool.DataAccessLayer.Entities.Test", "StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Tests__student_id__44FF419A");

                    b.Navigation("Exam");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("PRN222_TrackingTool.DataAccessLayer.Entities.User", b =>
                {
                    b.HasOne("PRN222_TrackingTool.DataAccessLayer.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .HasConstraintName("FK__Users__role_id__3C69FB99");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("PRN222_TrackingTool.DataAccessLayer.Entities.Exam", b =>
                {
                    b.Navigation("Tests");
                });

            modelBuilder.Entity("PRN222_TrackingTool.DataAccessLayer.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("PRN222_TrackingTool.DataAccessLayer.Entities.Students", b =>
                {
                    b.Navigation("LecturerStudentAssignments");

                    b.Navigation("Test");
                });

            modelBuilder.Entity("PRN222_TrackingTool.DataAccessLayer.Entities.Test", b =>
                {
                    b.Navigation("LecturerStudentAssignments");
                });

            modelBuilder.Entity("PRN222_TrackingTool.DataAccessLayer.Entities.User", b =>
                {
                    b.Navigation("Exams");

                    b.Navigation("LecturerStudentAssignments");
                });
#pragma warning restore 612, 618
        }
    }
}
